services:
  web:
    container_name: djangoapp
    build: .
    command: /djangoapp/scripts/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
      - /root/django-teste/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - redis
      - certbot
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot --webroot-path=/var/www/certbot --email jmbomfimme@gmail.com --agree-tos --no-eff-email -d painel.worldchip.com.br

volumes:
  redis-data:
  certbot-etc:
  certbot-var: